esphome:
  name: adcp_test
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: secret! wifi_ssid
  password: secret! wifi

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Adcp Test Fallback Hotspot"
    password: "w2D5Di71pia6"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: secret! api_psw

ota:
  password: secret! ota_psw

# adcp:
#   - id: adcp1
#     sensor: adc0

# sensor:
#   - platform: adc
#     id: adc0
#     pin: A0
#   - platform: adcp
#     id: d1in
#     power: D1
#   - platform: adcp
#     id: d2in
#     plexid: adcp1
#     power: D2